server:
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}:3306/online_utilities?&socketFactory=com.google.cloud.sql.mysql.SocketFactory
    username: root
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

  cloud:
    gcp:
      sql:
        database-name: online_utilities
        instance-connection-name: ${DB_CONNECTION_NAME}
        ip-types: PUBLIC
  sql:
    init:
      mode: always
      encoding: UTF-8
      continue-on-error: false
      schema-locations: classpath:data/schema.sql