server:
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: P@ssw0rd
    url: jdbc:mysql://localhost:3306/online_utilities
    username: root
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      encoding: UTF-8
      continue-on-error: false
      schema-locations: classpath:data/schema.sql
  thymeleaf:
    cache: false