server:
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false
  port: 5000
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${RDS_PASSWORD}
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-version: 1

  thymeleaf:
    cache: true
