server:
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:/opt/db/onlineutilities;shutdown=true&hsqldb.lock_file=false
#    username: sa
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
  thymeleaf:
    cache: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-version: 1
    baseline-on-migrate: true
    table: flyway_migration_history
#    user: sa
  sql:
    init:
      mode: never

