INSERT INTO tools (name, Title, description, seo_keyword, seo_description, seo_canonical_url,
                                    seo_og_title, seo_og_image, seo_og_type, seo_og_url, seo_og_description, related_1,
                                    related_2, related_10, related_9, related_8, related_7, related_6, related_5,
                                    related_4, related_3)
VALUES ('CovertBase64ToImage', 'Convert Base64 to Image', 'Easily convert Base64 data back to image.',
        'convert base64 to image, base64, image, convert, png, tiff, jpeg', 'Easily convert base64 to image online. ',
        'base64-to-image.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL),
       ('ProtectPdfWithPassword', 'Protect PDF with password',
        'Protect PDF with password. This site helps to protect your PDF by setting password.',
        'Protect PDF with password, pdf, protect, set password, pdf password',
        'Protect PDF with password. This site helps to protect your PDF by setting password.',
        '/protect-pdf-online.html', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL),
       ('DecodeBase64Online', 'Decode base64 online', 'Help to decode base-64 data to origin data',
        'decode base64 , decode base64 online, decode text to base64, decode file to base64, mime tools',
        'Help to decode base-64 data to origin data', 'https://onlineutilities.net/mime-tools/base64-decoder.html',
        'Decode base64 online', NULL, NULL, 'https://onlineutilities.net/mime-tools/base64-decoder.html',
        'decode base64 , decode base64 online, decode text to base64, decode file to base64, mime tools', 4, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, NULL),
       ('EncodeBase64Online', 'Encode Base64 online', 'Help to encode Base64 online. Support encode text and file.',
        'encode base64, encode base64 online, encode text to base64, encode file to base64, mime tools',
        'Help to encode Base64 online. Support encode text and file.',
        'https://onlineutilities.net/mime-tools/base64-encoder.html', 'Encode Base64 online', NULL, NULL,
        'https://onlineutilities.net/mime-tools/base64-encoder.html',
        'encode base64, encode base64 online, encode text to base64, encode file to base64, mime tools', 3, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, NULL);