name: Demo manual workflow
on:
  workflow_dispatch
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - run: Echo "Greeting ${{ github.event.inputs.name }}"